# Write your query or mutation herquery workspaceDeployments {
query workspaceDeployments {
  workspaceDeployments(
    releaseName: "false-radiation-8173"
    workspaceUuid: "clcfnm2eu017614jft8l8gg9w"
  )
  {
    config
    id
    status
    createdAt
    updatedAt
    workspace {users {emails {address, createdAt} }}
  }
}  
    
    

